modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="sbv"
version="1.0.0"
displayName="Shmello's better void"
credits="Its Mr. Shmello"
displayURL="https://theumcnetwork.com"
logoFile="logo.png"
authors="Its Mr. Shmello"
description='''
A Void Enhancement Mod
'''

[[dependencies.sbv]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"


[[dependencies.sbv]]
    modId="umccore"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sbv]]
    modId="jade"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sbv]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

